version: '3.1'
services:
  megadl:
    build:
       context: '.'
       dockerfile: ./Dockerfile       
    resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 250M
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
